### ISSUE TITLE
Songs not playing from several YouTube Videos

### ISSUE THREAD

**Issue by UnbreakCode** [the-jame/shaqbot#1]
YouTube has changed some stuff and now the bot won't play everything. Any fix/solution?

**Comment by the-jame** [comment]
Unfortunately this seems to be a Youtube API problem. They're not allowing videos that are considered "music" to be played currently. It's extremely frustrating.

**Comment by UnbreakCode** [comment]
I fixed it using ytdl-core^^

**Comment by the-jame** [comment]
Can you confirm if you forgot to install ytdl-core, fixing the bot overall or that you worked around the music limitation?

**Comment by UnbreakCode** [comment]
idk how but when reinstalling the bot I can't install sodium because I need VS 2015,but I have 2019 installed. and also I need node-opus which does not play a sound for me

**Comment by UnbreakCode** [comment]
hm interesting. now I can't play several songs too

**Comment by the-jame** [comment]
yes, youtube is intentionally blocking "music" from being played. no workaround at the moment.

**Comment by the-jame** [comment]
wanted to update you on this being 100% resolved. any video now plays.
